Feat/mobile-nav
Alacran-Studio/lpdd pull request #23
Opened 2024-10-24 04:52 UTC by galenom

Used [shadcn's sidebar](https://ui.shadcn.com/docs/components/sidebar) component to add a side menu. 

Anything in src/component/ui was autogenerated by the `npx shadcn@latest add sidebar` command. Shadcn is a collection of reusable components. Instead of packaging them in node_modules, it copy / pastes them into our codebase giving us ownership and control of the components.

@jvmontes by default this puts them in src/components/ui, which I know you just got rid of. I left them so you can distinguish which files were auto generated. Where would you prefer these are placed?

 
<img width="733" alt="Screenshot 2024-10-24 at 12 39 44 AM" src="https://github.com/user-attachments/assets/cd447e0d-497d-4e9c-afc2-a53d1c94839d">
<img width="582" alt="Screenshot 2024-10-24 at 12 07 03 AM" src="https://github.com/user-attachments/assets/35a81d5c-3b47-42eb-a02e-9efb25e9f924">
<img width="729" alt="Screenshot 2024-10-24 at 12 37 46 AM" src="https://github.com/user-attachments/assets/20b5b236-1422-43af-9931-1dbdca3131f2">

2024-10-24 18:55 UTC, jvmontes requested changes
Thanks for putting this together so quickly! My only concern here is that we might be adding code that isn't used, which might lead to some confusion. I would advocate for only committing what we're actually using for our specific use case, the sidebar. Looks like at least button, separator, sheet, and tooltip can safely be removed without affecting the functionality this PR is looking to accomplish. Open to the thoughts of others. @rogeruiz , care to chime in here?

2024-10-24 18:55 UTC, jvmontes commented on src/app/globals.css
> -      var(--background-end-color)) var(--background-start-color);
I believe this gave us a little gradient to the background of our app. It was from a white/black to blue. Was this causing issues with the sidebar?

2024-10-24 18:55 UTC, jvmontes commented on src/components/AppSidebar/index.tsx
> +];
We probably should create a common array referenced by the `AppSidebar` & `NavLinks` components. These will stay the same across both, and currently are duplicated across both files. When we add the Directory page, we'll need to edit both. Let's create a single array to reference in both places.

2024-10-24 18:55 UTC, jvmontes commented on src/components/AppSidebar/index.tsx
> +];
Sidenote, I do like having the links in all caps on the `NavLinks` on desktop and capital case on the SideBar. Would be cool if we could keep them that way, or if we want to do all upper case for consistency, down for that too. I would touch base with the designers to get their input.

2024-10-24 18:55 UTC, jvmontes commented on src/components/ui/sidebar.tsx
> +}
This is one seriously hefty file 😅 I hope we never run into any bugs and have to go in here and dig around... 😅 😅

2024-10-24 18:55 UTC, jvmontes commented on tailwind.config.ts
> +  plugins: [require("tailwindcss-animate")],
Looks like the script might've gone in here and changed things up with the spacing. I think we're using 2 spaces for tabs. Could you do a quick run through the files added/modified and make sure they're properly formatted?

2024-10-24 19:04 UTC, rogeruiz commented on src/components/ui/sidebar.tsx
> +}
AY YO, is this how big ShadCDN components are?! 

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDY1NDBlazR2cjRsNzVvZXZhNWVrOThocnI3ZDB4NDVld3JyNG5jcSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/WMymVhUGmmO4Pu8NGU/giphy-downsized-large.gif)

2024-10-24 20:05 UTC, jvmontes commented
I was running the branch and noticed a couple of UI defects. 
- In light mode, the "FullBrand" text "LPDD" is black, so it's not showing up on the dark blue background. 
- It looks like for some reason the borders on the directory were changed. We should keep the ones it had before (currently what it looks like on `main`)

2024-11-04 16:03 UTC, rogeruiz commented on src/app/globals.css
> -      var(--background-end-color)) var(--background-start-color);
yeah I added this back and didn't see much that would affect the feature of adding the mobile navigation. I think we can add it back without an issue.

```diff
diff --git a/src/app/globals.css b/src/app/globals.css
index 7f4eb92..5a9d621 100644
--- a/src/app/globals.css
+++ b/src/app/globals.css
@@ -59,6 +59,12 @@
 
 body {
   color: var(--foreground-color);
+  background: linear-gradient(
+      to bottom,
+      transparent,
+      var(--background-end-color)
+    )
+    var(--background-start-color);
 }
 
 @layer utilities {
```

2024-11-04 16:17 UTC, rogeruiz commented on src/lib/utils.ts
> +}
Neat little function. Is this from ShadCN, @galenom?

2024-11-04 16:17 UTC, rogeruiz commented on src/components/ui/sidebar.tsx
> +}
Having looked through the code, I think there's some of the subcomponents we could remove later on that we're not currently using. This ShadCDN stuff looks cool and very very thorough. Thanks for exposing me to it @galenom. 🆒

2024-11-09 22:24 UTC, rogeruiz commented on src/components/NavBar/index.tsx
> +        <FullBrand />
Looks like when this component was created, that's when the Link to the homepage lost its `text-white` class. Not a big deal. Mistakes happen! ❤️

2024-11-10 02:00 UTC, rogeruiz commented
@jvmontes this is almost done. Like this close 👌🏽 do you think you could take a look? The last thing is that the Mobile Menu doesn't close but in the ShadCN UI examples it does. I didn't get a chance to debug it more than that though. 

I'll see what's up with it tomorrow but I can't promise too much.

2024-11-10 20:29 UTC, jvmontes commented on src/components/ui/sidebar.tsx
Also, I did have merge conflicts within the `package-lock.json`, so I ended up just removing node_modules and package-lock, and re-ran `npm install` to generate a new one and I'll commit that.

2024-11-10 21:21 UTC, jvmontes commented on tailwind.config.ts
> +        foreground: "hsl(var(--foreground))",
@rogeruiz  I started to look into this. It seems that there's some work to do on the style side of things. For some of these, it renamed some variables (`--foreground-color` to `--foreground` without an update on `globals.css`, leaving it undefined), and added hsl (hue, saturation, lightness) to certain existing vars while they're still hex values in the globals.css file. 

I think the best approach here might be to follow their naming conventions and fill out as much as we can with what we have, and use discrepancy on the definition of the colors. 

Since we already had existing hex values for colors, it doesn't make sense to update them to use HSL if they're already working, so I'll remove that `hsl()` from those. For the shadcn variables (I'd been calling it ShadCDN lol) we'll keep them as hsl (all the `--sidebar` vars). 

I believe this should fix all the UI discrepancies I see between here and main.

2024-11-10 21:23 UTC, jvmontes commented
> @jvmontes this is almost done. Like this close 👌🏽 do you think you could take a look? The last thing is that the Mobile Menu doesn't close but in the ShadCN UI examples it does. I didn't get a chance to debug it more than that though.
> 
> I'll see what's up with it tomorrow but I can't promise too much.

I pulled down the branch and see what you mean. I'm working on fixing the UI issues. If you're able to look into this, maybe timebox it, and if you're not able to get it, we could address it later. THANK YOU for your leadership on getting this merge-ready!!!!!! 🙏🏼🙏🏼🙏🏼

2024-11-10 21:34 UTC, rogeruiz commented
> > @jvmontes this is almost done. Like this close 👌🏽 do you think you could take a look? The last thing is that the Mobile Menu doesn't close but in the ShadCN UI examples it does. I didn't get a chance to debug it more than that though.
> 
> > 
> 
> > I'll see what's up with it tomorrow but I can't promise too much.
> 
> 
> 
> I pulled down the branch and see what you mean. I'm working on fixing the UI issues. If you're able to look into this, maybe timebox it, and if you're not able to get it, we could address it later. THANK YOU for your leadership on getting this merge-ready!!!!!! 🙏🏼🙏🏼🙏🏼

Good news. My brain lead me down a documentation rabbit hole and found all [the docs for this sidebar](https://ui.shadcn.com/docs/components/sidebar) that @galenom linked to above.

I think I can tackle the fix and prep us for organizing the file into subfiles for [that other ticket](https://app.asana.com/0/1207992233793749/1208694960699969).

I would like to tackle the refactoring of the component into a `lib/` directory after this gets merged in. I think this PR is already getting too big.

2024-11-10 21:45 UTC, rogeruiz commented on src/components/ui/sidebar.tsx
LOL yes the Sidebar file had to be reformatted to our Prettier convention. The only thing I've done so far in that file is in this commit, b44ab685f9d3cd9b59fbb15432f7b64ff8b3b1f1.

But I did expect to see a bunch of merge conflicts coming through. Glad you resolved it though!

2024-11-10 22:11 UTC, jvmontes commented
Awwww - how kind of you to modify for visual accessibility. You win the
Good Samaritan award.

lol “ resolve merge conflicts “ = delete the whole file and just paste
yours - yup! 😄

Jorge Viramontes
​jorgeviramontes.com <http://www.jorgeviramontes.com/>


On Sun, Nov 10, 2024 at 3:46 PM Roger Steve Ruiz ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On src/components/ui/sidebar.tsx
> <https://github.com/Alacran-Studio/lpdd/pull/23#discussion_r1835789129>:
>
> LOL yes the Sidebar file had to be reformatted to our Prettier convention.
> The only thing I've done so far in that file is in this commit, b44ab68
> <https://github.com/Alacran-Studio/lpdd/commit/b44ab685f9d3cd9b59fbb15432f7b64ff8b3b1f1>
> .
>
> But I did expect to see a bunch of merge conflicts coming through. Glad
> you resolved it though!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Alacran-Studio/lpdd/pull/23#discussion_r1835789129>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAS4NR5LN4PZE4UYYTVNYNDZ77H2FAVCNFSM6AAAAABQQGWTDKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMRVHA2TSNBQG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-11 00:28 UTC, jvmontes approved these changes

2024-11-11 00:29 UTC, jvmontes commented
@rogeruiz I've approved this. Feel free to tackle closing the menu sidebar when an item is selected. But to me, for now, that's not a showstopper from getting this merged. And I also agree that moving the components should be in a separate PR, this one is big enough as it is. I've tested light and dark mode and the colors should all be working as expected now. Those HSL pieces will getya!!

2024-11-11 22:39 UTC, rogeruiz commented
I'm gonna merge this in now. I've cleaned up the colors for the `<FullBrand/>`
component since it's different across the mobile menu and the desktop menu. I've
also added the logo as an embedded SVG named `LogoSvg` in the component too so I
could set the `fill=` attribute to a CSS variable. This also meant I needed to
plumb some props across this component too.

Let's add any tickets if you find something after the merge. I'm gonna go focus
on #28 now.

2024-11-11 22:39 UTC, merged