Fix: Prevent directory container resizing with filter dropdown
Alacran-Studio/lpdd pull request #31
Opened 2024-11-08 21:57 UTC by fgonza23

Overview
This pull request resolves a UI bug where toggling the "Filter by Industry" dropdown caused the directory container width to jump and resulted in disappearing industry chips.

Problem
Issue: When industries were selected for filtering, the directory container would resize slightly upon toggling the filter button. Additionally, the industry chips would not display as expected when the dropdown was open.
Cause: The layout shift occurred because the chip container was dynamically added/removed, impacting the container’s dimensions.

Solution
Persistent Chip Container: Added a reserved space for the industry chips, even when no industries are selected, to prevent layout shifts.
Dropdown Alignment Fix: Adjusted the dropdown menu positioning to align directly under the filter button when opened.

Changes
Updated Filter component to keep chip space consistent.
CSS adjustments for dropdown alignment under the filter button.

Testing
Verified fixed-width directory container when toggling the filter.
Confirmed that selected industry chips display consistently without layout changes.

2024-11-08 22:23 UTC, rogeruiz requested changes
❌ This PR needs changes ...

Bien esfuerzo en esto @fgonza23. But there's some issues I noticed while testing on mobile. I think this affects all sizes though. There's no space between the little tag pills and the dropdown. We'll need to add some padding or margins to the dropdown or the pill container. 


<details open>
<summary>📸  Screenshot(s)</summary>

https://github.com/user-attachments/assets/b28d1e3f-3b82-42a3-81c4-60db312f1ee3
</details>

2024-11-08 22:23 UTC, rogeruiz commented on src/components/Directory/Filter/index.tsx
> +          <FilterIcon />
Nice work on cleaning these up.

2024-11-08 22:23 UTC, rogeruiz commented on src/components/Directory/Filter/index.tsx
> +        }`}
Interesting approach. Did we want to make the items in here invisible? I thought we'd just leave them up since they're visibly blocked from view by the dropdown. What do you think @countaight, @geraxrodriguez, @jvmontes? If we decide to not hide/show, we could use the suggested code changes below to just have it appear permanently whether it's open or not.

```suggestion
        className={`flex h-16 w-full min-w-[300px] flex-wrap gap-2`}
```

2024-11-08 22:23 UTC, rogeruiz commented on src/components/Directory/Filter/index.tsx
>              : "max-h-0 translate-y-0 border-none p-0 opacity-0 shadow-none"
[If we decide to not have animations here](https://github.com/Alacran-Studio/lpdd/pull/31#discussion_r1835103221), we would also need to change this part so it's not using `isIndustryDropdownOpen` boolean along with removing the `transition-all`, `duration-300`, and `ease-out` classes as well.

2024-11-08 22:23 UTC, rogeruiz commented on src/components/Directory/Filter/index.tsx
> +        }`}
Actually. I realize now that this is for the actual dropdown and not hiding and showing the tags. You can disregard that part. But I'm curious if we want animation here or not. I won't block this PR on whether or not it has animations though.

2024-11-08 22:23 UTC, rogeruiz commented on src/components/Directory/Filter/index.tsx
> -          selectedIndustries.length === 0 ? "mt-0" : "mt-4"
I think this is the issue causing the collapse I mentioned in my request changes comment.

2024-11-08 22:23 UTC, rogeruiz commented on src/components/Directory/Filter/index.tsx
> -          selectedIndustries.length === 0 ? "mt-0" : "mt-4"
We probably just always want it to be `mt-4` all the time now.

2024-11-08 22:29 UTC, jvmontes commented
> ❌ This PR needs changes ...
> 
> Bien esfuerzo en esto @fgonza23. But there's some issues I noticed while testing on mobile. I think this affects all sizes though. There's no space between the little tag pills and the dropdown. We'll need to add some padding or margins to the dropdown or the pill container.
> 
> 📸 Screenshot(s)
>  trim.B5FA7262-7FF8-439F-9A58-BFCEA9887857.MOV

Yeah it looks like the chips are definitely being smooshed a bit. For reference, here's a screenshot of what it looks like on main (accessible at https://lpdd.netlify.app )

![Screen Shot 2024-11-08 at 4 28 49 PM](https://github.com/user-attachments/assets/76c855d9-6336-4997-8d88-3b537f5fed16)

2024-11-08 22:37 UTC, jvmontes commented
https://github.com/user-attachments/assets/9c0e5f36-610f-49c2-87a4-e51bc986d7b7

I noticed that when I open the filter, the boxes don't flow into the filter anymore. The boxes appear at the end once the Industry titles populate. We should make sure that works as smoothly as it did before.

2024-11-09 00:02 UTC, jvmontes approved these changes
Good start, @fgonza23 ! Check out the commit I added and play around with it to see the final product. 👏🏼

2024-11-09 00:08 UTC, jvmontes commented on src/components/Directory/Filter/index.tsx
> +        }`}
> When I remove the line of code making the chips container invisible, it looks fine, except that the filter dropdown animates from the bottom left, and just looks a little off. I wish it would actually _drop down_ from the filter button in terms of the animation. @countaight you said you were good at animations, any insights around this would be much appreciated!

@countaight nevermind, I got it to work nicely!

2024-11-09 01:31 UTC, rogeruiz approved these changes
lgtm 🌈 

¡Que chimba! Looks great @fgonza23 y @jvmontes. 


<details open>
<summary>📸  Screenshot(s)</summary>

https://github.com/user-attachments/assets/fad60fb4-03b6-4a19-9d2e-7f77394a8bc2
</details>

2024-11-09 06:03 UTC, merged