feat: Adding `<Logo/>` and `<Tags/>` components with updated colors too
Alacran-Studio/lpdd pull request #34
Opened 2024-11-14 01:12 UTC by rogeruiz

- [x] **feat: Refactoring Directory/Logo into component**
- [x] **fix: Updating colors**
- [x] **feat: Adding new Directory/Tags component**

2024-11-14 21:21 UTC, jvmontes requested changes
let's get aligned with the colors, but i love what u did with the Logo and Tags components!

2024-11-14 21:56 UTC, rogeruiz commented on src/app/globals.css
> +    --accent-color: #dba41a;
I used a tool called Coolers.co which allows me to shade colors down to get a dark mode equivalent

2024-11-14 21:57 UTC, rogeruiz commented on src/app/globals.css
> +  --accent-color: #f0d07d;
I can change those and the dark colors into HSL later today.

2024-11-14 22:01 UTC, rogeruiz commented on src/app/globals.css
> +  --accent-color: #f0d07d;
Also CSS variables can hold arbitrary strings, I'd like for the name of the variable to hold the type of value it is. But we don't need to include the word color in the Tailwind configuration.

2024-11-16 04:55 UTC, rogeruiz commented
@jvmontes Okay I've updated all the colors to use `hsl()` and moved the call to that function in to the variable declaration rather than where we're referencing the variable. This way we can modify the colors from `hsl()` if we need to. If there's more feedback about colors, I'd feel better to change things in other PRs rather than in this PR. I still need this to be stable before I can get started on the Org Details page again.

2024-11-16 21:30 UTC, jvmontes commented on tailwind.config.ts
> +        // secondary: "var(--secondary)",
nitpick but we could probably uncomment this even if it isn't used.

2024-11-16 21:30 UTC, jvmontes approved these changes
Looks good! Approved 👍🏼

2024-11-16 22:20 UTC, merged